### ISSUE TITLE
File access does not seem to work...

### ISSUE THREAD

**Issue by KeithHenrickson-Retro** [hth313/Calypsi-6502-Commodore#2]
I think there is an issue in _stub_open and an issue in _stub_read.

In _stub_read, there is the following line:
__set_logical_file(fd, device, 255);

That sets the SA to 255. Technically for commodore drives, SAs were in the range 0-15, with the following assignments:

0 = PRG load
1 = PRG save
2-14 = Data file access
15 = Disk controller

I'm not sure what a drive would do with the 255 SA, honestly. I patched around this while chasing down the other problem. Conventionally, most programs just used the same SA as they were using the file number, because both numbers had the same range, so a conflict between multiple open files would never occur.

In _stub_read, there's the following check:
	      cpx     #3	    ; test for stdout/stderr
	      bcs     eof$

That causes a branch to eof$ if the program ever attempts to read from file descriptors 3 or higher, which basically means all data files opened by _stub_open cannot be read from. I patched this one out in memory, and the data file was now readable.

**Comment by hth313** [comment]
Feel free to make a PR for any fixes you make. I looked at a couple of documentation pages for the Commodore kernal and they were not all the crystal clear.

**Comment by hth313** [comment]
I think the `bcs` should be a `bcc`. The idea is to cause `stdout` and `stderr` (file descriptor 1 and 2) to return `EOF` as they cannot be read.

**Comment by KeithHenrickson-Retro** [comment]
PR is up!

And yes, most Commodore documentation is... unclear. File access in ML is by far the most frustrating!

**Comment by hth313** [comment]
Thanks! I merged it and updated Calypsi to use it in the next release build. If you find more issues, additional PRs are welcome.
